"""empty message

Revision ID: 2633cec2eff0
Revises: 
Create Date: 2025-02-11 14:34:18.471677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2633cec2eff0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('national_id', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('employer',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('employer', sa.String(length=150), nullable=False),
    sa.Column('employer_supervisor', sa.String(length=150), nullable=False),
    sa.Column('project_manager', sa.String(length=150), nullable=False),
    sa.Column('main_colleague', sa.String(length=150), nullable=False),
    sa.Column('contract_number_employer', sa.String(length=100), nullable=False),
    sa.Column('contract_number_university', sa.String(length=100), nullable=False),
    sa.Column('contract_date', sa.String(length=100), nullable=False),
    sa.Column('contract_period', sa.String(length=100), nullable=False),
    sa.Column('contract_state', sa.String(length=100), nullable=False),
    sa.Column('contract_price', sa.Integer(), nullable=False),
    sa.Column('contract_insurance_percentage', sa.Float(), nullable=False),
    sa.Column('contract_guarantee_performance_percentage', sa.Float(), nullable=False),
    sa.Column('contract_tax_percentage', sa.Float(), nullable=False),
    sa.Column('contract_university_overhead_percentage', sa.Float(), nullable=False),
    sa.Column('contract_weri_overhead_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number_employer'),
    sa.UniqueConstraint('contract_number_university'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_status',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project_employee',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], )
    )
    op.create_table('received_employer',
    sa.Column('re_project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('requested_date', sa.String(length=100), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('requested_letter_number', sa.String(length=100), nullable=False),
    sa.Column('requested_description', sa.Text(), nullable=False),
    sa.Column('received_date', sa.String(length=100), nullable=False),
    sa.Column('received_amount', sa.Integer(), nullable=False),
    sa.Column('received_letter_number', sa.String(length=100), nullable=False),
    sa.Column('received_description', sa.String(length=500), nullable=False),
    sa.Column('insurance_percentage', sa.Float(), nullable=False),
    sa.Column('guarantee_performance_percentage', sa.Float(), nullable=False),
    sa.Column('university_overhead_percentage', sa.Float(), nullable=False),
    sa.Column('weri_overhead_percentage', sa.Float(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['re_project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_employees',
    sa.Column('pe_employee_id', sa.Integer(), nullable=False),
    sa.Column('pe_project_id', sa.Integer(), nullable=False),
    sa.Column('pe_received_employer_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.String(length=100), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('payment_description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pe_employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['pe_project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['pe_received_employer_id'], ['received_employer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_employees')
    op.drop_table('received_employer')
    op.drop_table('project_employee')
    op.drop_table('user')
    op.drop_table('project_status')
    op.drop_table('project')
    op.drop_table('employer')
    op.drop_table('employee')
    # ### end Alembic commands ###
