"""empty message

Revision ID: 3645dd5b6b72
Revises: 2633cec2eff0
Create Date: 2025-02-11 17:16:56.125928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3645dd5b6b72'
down_revision = '2633cec2eff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
