"""empty message

Revision ID: 39ca3d542e90
Revises: 1a94fc544221
Create Date: 2025-02-11 17:53:36.854567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ca3d542e90'
down_revision = '1a94fc544221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
